# Generated by Django 4.2 on 2023-04-10 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('title', '0003_alter_titlemodel_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlemodel',
            name='writer',
            field=models.ForeignKey(default=None, null=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
