# Generated by Django 4.2 on 2023-04-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postermodel',
            name='image',
            field=models.FileField(null=True, upload_to='imgs/'),
        ),
    ]
